import os
import sys
import json
import argparse
import yaml
from langchain_google_genai import ChatGoogleGenerativeAI

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from tools.github_client import get_pr_file_content, create_issue
from state.checkpoint_manager import save_checkpoint


def load_team_config():
    """Load team prompt configuration if available."""
    config_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
                              ".github", "agent-templates")
    configs = []
    if os.path.exists(config_dir):
        for f in os.listdir(config_dir):
            if f.endswith(".yaml") or f.endswith(".yml"):
                with open(os.path.join(config_dir, f)) as fh:
                    configs.append(yaml.safe_load(fh))
    return configs


def load_project_policy():
    """Load the Jira project policy for context."""
    policy_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
                               "project-policy.yaml")
    if os.path.exists(policy_path):
        with open(policy_path) as f:
            return yaml.safe_load(f)
    return {}


def run_pm_agent(prd_text, team_configs, project_policy):
    """Use Gemini to break a PRD into Epics, Stories, and Acceptance Criteria."""
    llm = ChatGoogleGenerativeAI(model="gemini-2.0-flash", temperature=0)

    team_context = ""
    for cfg in team_configs:
        if cfg.get("prompt_instructions"):
            team_context += f"\n\nTeam '{cfg.get('team_name', 'unknown')}' guidelines:\n{cfg['prompt_instructions']}"

    policy_context = ""
    if project_policy:
        jira_cfg = project_policy.get("jira_configuration", {})
        issue_types = jira_cfg.get("issue_types", [])
        policy_context = f"\n\nAvailable Jira issue types: {', '.join(issue_types)}"

    prompt = f"""You are an Expert Agile Product Manager. Break the following PRD into a structured backlog.

OUTPUT FORMAT (strict markdown):
## Epics
For each epic, provide a title and short description.

## User Stories
For each story, provide:
- **Story Title**
- **As a** [role], **I want** [action] **so that** [benefit]
- **Acceptance Criteria** (Given/When/Then format)
- **Story Points** (fibonacci: 1,2,3,5,8,13)
- **Priority** (Critical, High, Medium, Low)

{policy_context}
{team_context}

---
PRD TEXT:
{prd_text}
"""
    response = llm.invoke(prompt)
    return response.content


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--pr", required=True, help="Pull request number containing the PRD")
    args = parser.parse_args()

    pr_number = args.pr
    repo = os.environ.get("GITHUB_REPOSITORY", "SumitSahacatiim2010/Requirements-test")
    token = os.environ.get("GITHUB_TOKEN")

    if not token:
        print("Error: GITHUB_TOKEN not set")
        sys.exit(1)

    # 1. Fetch PRD content from the PR
    print(f"[PM Agent] Fetching PRD from PR #{pr_number}...")
    prd_text = get_pr_file_content(repo, pr_number, token)
    if not prd_text:
        print("[PM Agent] No markdown PRD files found in PR. Exiting.")
        sys.exit(1)
    print(f"[PM Agent] Fetched {len(prd_text)} chars of PRD text.")

    # 2. Load configurations
    team_configs = load_team_config()
    project_policy = load_project_policy()
    print(f"[PM Agent] Loaded {len(team_configs)} team config(s), policy: {'yes' if project_policy else 'no'}")

    # 3. Run Gemini PM Agent
    print("[PM Agent] Invoking Gemini 2.0 Flash...")
    backlog_markdown = run_pm_agent(prd_text, team_configs, project_policy)
    print("[PM Agent] Backlog generated successfully.")

    # 4. Create GitHub Issue for HITL review
    issue_body = (
        f"## 📋 Draft Backlog for PR #{pr_number}\n\n"
        f"_Generated by PM Agent using Google Gemini_\n\n"
        f"{backlog_markdown}\n\n"
        f"---\n"
        f"### ✅ Actions\n"
        f"- Comment **`/approve`** to push these stories to Jira\n"
        f"- Comment **`/revise [feedback]`** to request changes\n"
    )
    try:
        issue = create_issue(
            repo,
            f"Draft Backlog Review: PR #{pr_number}",
            issue_body,
            token
        )
        issue_number = issue["number"]
        print(f"[PM Agent] Created Issue #{issue_number}: {issue['html_url']}")
    except Exception as e:
        print(f"[PM Agent] ERROR creating GitHub Issue: {e}")
        sys.exit(1)

    # 5. Save checkpoint state for /approve resumption
    state = {
        "pr_number": pr_number,
        "issue_number": issue_number,
        "prd_text": prd_text,
        "backlog_markdown": backlog_markdown,
        "status": "awaiting_approval",
    }
    save_checkpoint(repo, token, issue_number, state)
    print(f"[PM Agent] Checkpoint saved. Waiting for /approve on Issue #{issue_number}.")


if __name__ == "__main__":
    main()
